# The `common' part is automatically included (and possibly overriden by all
# other flavors)
common:

    # Bucket for storage
    boto_bucket: _env:S3_BUCKET

    loglevel: info

    # Amazon S3 Storage Configuration
    s3_access_key: _env:AWS_ACCESS_KEY_ID
    s3_secret_key: _env:AWS_SECRET_KEY
    s3_bucket: _env:S3_BUCKET
    s3_encrypt: False
    s3_secure: True

    # Set a random string here
    secret_key: _env:SECRET_KEY

dev:
    storage: local
    storage_path: /var/local/docker-registry

prod:
    storage: s3
    storage_path: /
