# The `common' part is automatically included (and possibly overriden by all
# other flavors)
common:

    loglevel: info
    standalone: 1

    # Amazon S3 Storage Configuration
    s3_access_key: _env:DOCKER_REGISTRY_AWS_ACCESS_KEY_ID
    s3_secret_key: _env:DOCKER_REGISTRY_AWS_SECRET_KEY
    s3_bucket: _env:DOCKER_REGISTRY_S3_BUCKET
    s3_encrypt: 0
    s3_secure: 1

    # Set a random string here
    secret_key: _env:DOCKER_REGISTRY_SECRET_KEY

dev:
    storage: local
    storage_path: /var/local/docker-registry

s3:
    storage: s3
    storage_path: /
